"""config — Centralized workflow constants."""

from workflow.config.paths import (
    WORKFLOW_ROOT,
    DEFAULT_STATE_PATH,
    LOG_FILE,
    DEBUG_LOG_FILE,
)
from workflow.config.constants import (
    AGENT_ONLY_PHASES,
    AGENT_PLUS_WRITE_PHASES,
    CODING_PHASES,
    PLAN_ALLOWED_STOP_PHASES,
    EXPLORE_MAX,
    RESEARCH_MAX,
    PLAN_MAX,
    PLAN_REVIEW_MAX,
    TEST_REVIEWER_MAX,
    VALIDATOR_MAX,
    PLAN_REVIEW_THRESHOLD,
    CODE_EXTENSIONS,
    TEST_PATH_PATTERNS,
    CODEBASE_MD,
    PR_COMMAND_PATTERNS,
    TEST_RUN_PATTERNS,
    CI_CHECK_PATTERNS,
    STORY_ID_PATTERN,
    REQUIRED_SECTIONS,
    SAFE_DOMAINS,
)
